### ISSUE TITLE
Edit AndroidManifest.xml

### ISSUE THREAD

**Issue by Swisyn** [tslamic/premiumer#1]
Thank you for the library.

This line should be removed in AndroidManifest.xml for the libraries;

 <application
        android:allowBackup="true"
        android:label="@string/app_name" />

**Comment by tslamic** [comment]
Hi Cüneyt,

thanks for reporting this, it'll be fixed over the weekend. 

Cheers,
Tadej

**Comment by Glurt** [comment]
Did you get around to fixing this?

**Comment by tslamic** [comment]
Apologies, I haven't had the chance to fix this yet. Perhaps a pull request would make things easier? :innocent:

**Comment by SandroMachado** [comment]
Fixed by #3.

@tslamic great library! Thanks for your work.

**Comment by SandroMachado** [comment]
For those who want to override the library configuration, just add `tools:replace="android:allowBackup"` to you application tag.

**Comment by tslamic** [comment]
Hi guys, sorry you had to wait for ages. Premiumer v2 is out and this has been fixed.
