### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by SandroMachado** [tslamic/premiumer#4]
@tslamic do you have plans to keep the active development at `premiumer`? 

Thanks for your work.

**Comment by tslamic** [comment]
Hi @SandroMachado,

let me first apologize for not replying sooner - I’m absolutely swamped with work right now and have very little time for my side projects. 

As it is, I consider premiumer feature complete - I have no intentions to extend the API or functionality, unless a particular feature would come handy for majority of the users. Is there anything in particular you had in mind?

Thank you for your contribution, I'll merge your changes in ASAP!

**Comment by SandroMachado** [comment]
Hi @tslamic,

I have a few crashes on production related to the lib, so I will probably do some PR to fix them. 
I also want to remove my workaround to fix the issue #1 so I need a new release with the #3 merged. 

Thanks for your great work!

**Comment by SandroMachado** [comment]
Looks like it not under active development. I made a fork, merged the two PR and made a release. If anyone need this, it is available here: https://github.com/SandroMachado/premiumer
