### ISSUE TITLE
IllegalArgumentException: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by Toxa2033** [tslamic/premiumer#5]
Error when purchase 
`0java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
1   at android.support.v4.app.BaseFragmentActivityEclair.checkForValidRequestCode(BaseFragmentActivityEclair.java:64)
2   at android.support.v4.app.BaseFragmentActivityEclair.startIntentSenderForResult(BaseFragmentActivityEclair.java:45)
3   at android.support.v4.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:75)
4   at io.github.tslamic.prem.Premiumer.purchase(Premiumer.java:214)
5   at ru.houseofapps.antigai.Activities.BuyProActivity$1.onClick(BuyProActivity.java:71)
6   at android.view.View.performClick(View.java:4480)
7   at android.view.View$PerformClick.run(View.java:18686)
8   at android.os.Handler.handleCallback(Handler.java:733)
9   at android.os.Handler.dispatchMessage(Handler.java:95)
10  at android.os.Looper.loop(Looper.java:157)
11  at android.app.ActivityThread.main(ActivityThread.java:5872)
12  at java.lang.reflect.Method.invokeNative(Native Method)
13  at java.lang.reflect.Method.invoke(Method.java:515)
14  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
15  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:668)
16  at dalvik.system.NativeStart.main(Native Method)`

**Comment by tslamic** [comment]
Premiumer v2 released, this issue has been fixed.
