### ISSUE TITLE
Not clear sample app!

### ISSUE THREAD

**Issue by hatimmakki** [tslamic/premiumer#6]
Hi
Could you give a sample app or codes that, for example, hide an image if user purchased, and show it if he didn't. Also, a button to purchase.

thanks

**Comment by tslamic** [comment]
Hi,

the sample app does exactly this. If you follow the code [here](https://github.com/tslamic/premiumer/blob/master/app/src/main/java/io/github/tslamic/premiumer/MainActivity.java), `mAds` is a simple `View` instance. To initiate a purchase, your button should invoke a method similar to `MainActivity. onPurchase`.
