### ISSUE TITLE
onPurchase (mPremiumer.purchase(this);) exception 

### ISSUE THREAD

**Issue by hatimmakki** [tslamic/premiumer#7]
Hi
the method onPurchase throws an error when my button call it.
The exact line:
`final boolean enqueued = mPremiumer.purchase(this);`
Exception type:
`Method threw 'java.lang.IllegalArgumentException' exception.`
Message:
`Can only use lower 16 bits for requestCode`

It happens while running it on real Pexil XL device.

**Comment by tslamic** [comment]
Hi,

thanks for reporting this. Will be fixed in the next release, hopefully beginning of next week, unless you wish to contribute. ;)

Thanks.

**Comment by hatimmakki** [comment]
When next release will be published?

**Comment by tslamic** [comment]
Hi, v2 will be available tomorrow or Wednesday at the latest.

**Comment by tslamic** [comment]
Hi, v2 candidate is available in the `dev` branch. Not pushed to maven central yet, so you'll have to clone/fork it and import it as a library. Happy coding!

**Comment by tslamic** [comment]
Premiumer v2 released.
