### ISSUE TITLE
error "Cannot resolve symbol'with'"

### ISSUE THREAD

**Issue by hatimmakki** [tslamic/premiumer#8]
Hi
Thanks for v2, and that's really gr8 work.

Here is my issue.
When I create the instance:
`Premiumer mPremiumer = new PremiumerBuilder.with(context)
                .sku(SKU)
                .listener(this)
                .build();`
It shows that I have a problem with ".with(context)"
The error is:
`Cannot resolve symbol'with'`

any help with this?

thanks

**Comment by tslamic** [comment]
Hi, 

just remove `new` keyword as `PremiumerBuilder.with(Context)` is a static factory method:
```java
Premiumer premiumer = PremiumerBuilder.with(context).sku(SKU).listener(this).build();
```
