### ISSUE TITLE
D/LogListener: onFailedToConsumeSku()

### ISSUE THREAD

**Issue by hatimmakki** [tslamic/premiumer#9]
Hi
The purchase works well with me. My tester account purchased, and the ads now are hidden. perfect
But, I want to cancel the payment in order to test the purchase again, so I called the onConsume() method, but i got this log message:
`D/LogListener: onFailedToConsumeSku()`
any help?

thanks

**Comment by tslamic** [comment]
Hi,

unfortunately you haven't provided enough information to pinpoint the problem. I suggest you clear all vending-related cached data via adb:

```
adb shell pm clear com.android.vending
```

and try again. If the problem persists, please open a new issue describing the reproduction steps.

Thanks.
